import { Product } from './product.model';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'berdux-1',
    name: 'Berdux 140cm',
    brand: 'berdux',
    category: 'fluegel',
    subCategory: 'Akustischer Flügel',
    price: 12800,
    priceDisplay: '12.800 €',
    description:
      'Spitzenqualität in München ca. 1965 gebaut! Bestens reguliert, intoniert und gestimmt!',
    images: [
      'assets/images/pianos/berdux-1/image_1.jpg',
      'assets/images/pianos/berdux-1/image_2.jpg',
    ],
    specs: {
      condition: 'Restauriert',
      originalPrice: '18.500 €',
      buildYear: 'ca. 1965',
      height: '102 cm',
      width: '140 cm',
      depth: '150 cm',
      weight: '250 kg',
      pedals: '2 (Dämpfer, Una Corda)',
      finish: 'Nussbraun',
    },
  },
  {
    id: 'fazioli-1',
    name: 'Fazioli F183',
    brand: 'fazioli',
    category: 'fluegel',
    subCategory: 'Akustischer Flügel',
    price: 64000,
    priceDisplay: '64.000 €',
    description:
      'Wenig gespielter Konzertflügel der Spitzenmarke Fazioli. 1. Hand! Begeisternde Spielart und herrlicher Ton! Bj. ca. 1997!',
    images: ['assets/images/pianos/fazioli-1/image_1.jpg'],
    specs: {
      condition: 'Gebraucht',
      buildYear: 'ca. 1997',
      height: '102 cm',
      width: '183 cm',
      depth: '186 cm',
      weight: '320 kg',
      pedals: '3 (Dämpfer, Una Corda, Sostenuto)',
      finish: 'Schwarz poliert',
    },
  },
  {
    id: 'steinway-1',
    name: 'Steinway & Sons O-180',
    brand: 'steinway',
    category: 'fluegel',
    subCategory: 'Akustischer Flügel',
    price: 46900,
    priceDisplay: '46.900 €',
    description:
      'Perfekt überarbeiteter Salonflügel von Steinway Hamburg! Bj ca 1978!',
    images: [
      'assets/images/pianos/steinway-1/image_1.jpg',
      'assets/images/pianos/steinway-1/image_2.jpg',
    ],
    specs: {
      condition: 'Restauriert',
      originalPrice: '85.000 €',
      buildYear: 'ca. 1978',
      height: '102 cm',
      width: '180 cm',
      depth: '186 cm',
      weight: '310 kg',
      pedals: '3 (Dämpfer, Una Corda, Sostenuto)',
      finish: 'Schwarz poliert',
    },
  },
  {
    id: 'schimmel-1',
    name: 'Schimmel 180cm',
    brand: 'schimmel',
    category: 'fluegel',
    subCategory: 'Akustischer Flügel',
    price: 23900,
    priceDisplay: '23.900 €',
    description:
      'Flügel Schimmel aus 1. priv.Hand! 1990 neu gekauft! Präzise Spielart schöner Klang!',
    images: [
      'assets/images/pianos/schimmel-1/image_1.jpg',
      'assets/images/pianos/schimmel-1/image_2.jpg',
    ],
    specs: {
      condition: 'Gebraucht',
      height: '102 cm',
      width: '180 cm',
      depth: '186 cm',
      weight: '310 kg',
      pedals: '3 (Dämpfer, Una Corda, Sostenuto)',
      finish: 'Weiß poliert',
    },
  },
  {
    id: 'bechstein-1',
    name: 'C. Bechstein Mod. 11',
    brand: 'bechstein',
    category: 'klaviere',
    subCategory: 'Akustisches Klavier',
    price: 15800,
    priceDisplay: '15.800 €',
    description:
      'Wunderschönes Piano der Spitzenklasse von C. Bechstein Modell 11,  121 cm H,  ca. 1930 Berlin.',
    images: [
      'assets/images/pianos/bechstein-1/image_1.jpg',
      'assets/images/pianos/bechstein-1/image_2.jpg',
    ],
    specs: {
      condition: 'Restauriert',
      buildYear: 'ca. 1930',
      height: '121 cm',
      width: '150 cm',
      depth: '60 cm',
      weight: '220 kg',
      pedals: '2 (Dämpfer, Una Corda)',
      finish: 'Schwarz poliert',
    },
  },
  {
    id: 'steinweg-1',
    name: 'Grotrian Steinweg 130',
    brand: 'steinweg',
    category: 'klaviere',
    subCategory: 'Akustisches Klavier',
    price: 8900,
    priceDisplay: '8.900 €',
    description:
      'Konzert-Klavier der Spitzenklasse ca. 1925 Braunschweig. Restauriert, reguliert, intoniert und gestimmt.',
    images: [
      'assets/images/pianos/steinweg-1/image_1.jpg',
      'assets/images/pianos/steinweg-1/image_2.jpg',
    ],
    specs: {
      condition: 'Restauriert',
      buildYear: 'ca. 1925',
    },
  },
  {
    id: 'mendelson-1',
    name: 'Ed. Mendelson 113cm',
    brand: 'mendelson',
    category: 'klaviere',
    subCategory: 'Akustisches Klavier',
    price: 4900,
    priceDisplay: '4.900 €',
    description:
      'Klangvolles Klavier mit Deckelbremse, angelegten Konsolen, schwarz poliert!',
    images: [
      'assets/images/pianos/mendelson-1/image_1.jpg',
      'assets/images/pianos/mendelson-1/image_2.jpg',
    ],
    specs: {
      condition: 'Gebraucht',
      height: '113 cm',
      width: '145 cm',
      depth: '57 cm',
      weight: '200 kg',
      pedals: '2 (Dämpfer, Una Corda)',
      finish: 'Chrom',
    },
  },
  {
    id: 'mendelson-2',
    name: 'Ed. Mendelson 105',
    brand: 'mendelson',
    category: 'digitalpianos',
    subCategory: 'Digitalpiano',
    price: 2300,
    priceDisplay: '2.300 €',
    description:
      'Ein Piano mit klasssischer Klavierform der Extra-Preis-Leistungsklasse.',
    images: ['assets/images/pianos/mendelson-2/image_1.jpg'],
    specs: {
      condition: 'Neu',
      height: '105 cm',
      width: '135 cm',
      depth: '40 cm',
      weight: '50 kg',
      pedals: '3 (Dämpfer, Una Corda, Sostenuto)',
      finish: 'Schwarz matt',
    },
  },
  {
    id: 'yamaha-1',
    name: 'Yamaha Modus F11',
    brand: 'yamaha',
    category: 'digitalpianos',
    subCategory: 'Selbstspieler-Digitalpiano',
    price: 5900,
    priceDisplay: '5.900 €',
    description:
      'Sensationelles Sondermodell von Yamaha! Perfekte Pianoklänge, angenehme Spielart!',
    images: ['assets/images/pianos/yamaha-1/image_1.jpg'],
    specs: {
      condition: 'Neu',
      height: '110 cm',
      width: '140 cm',
      depth: '45 cm',
      weight: '60 kg',
      pedals: '3 (Dämpfer, Una Corda, Sostenuto)',
      finish: 'Schwarz poliert',
    },
  },
];
